BEGIN;

DROP TABLE IF EXISTS checkbox_answers CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS responses CASCADE;
DROP TABLE IF EXISTS view_permissions CASCADE;
DROP TABLE IF EXISTS mcq_options CASCADE;
DROP TABLE IF EXISTS checkbox_options CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS sections CASCADE;
DROP TABLE IF EXISTS published_forms CASCADE;
DROP TABLE IF EXISTS draft_forms CASCADE;
DROP TABLE IF EXISTS users CASCADE;

COMMIT;